name: Deploy
on:
  push:
    branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '21'
                cache: 'maven'

            - name: Maven Wrapper permissions
              run: chmod +x ./mvnw

            - name: Build with Maven for Docker
              run: ./mvnw clean package -DskipTests

            - name: Build Docker image
              run: |
                docker build \
                  -t pedro084/api-for-evaluating-cinematographic-works:${{ github.sha }} \
                  -t pedro084/api-for-evaluating-cinematographic-works:latest .

            - name: Login Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Push Docker image
              run: |
                docker push pedro084/api-for-evaluating-cinematographic-works:${{ github.sha }}
                docker push pedro084/api-for-evaluating-cinematographic-works:latest

            - name: Credentials of AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Force Deploy in AWS ECS
              run: aws ecs update-service --cluster ecw-cluster --service api-ecw-service --force-new-deployment