name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        services:
          db:
            image: postgres:15-alpine
            env:
              POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
              POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
              POSTGRES_DB: ecw_db
              TMDB_SECRET_TOKEN: ${{ secrets.TMDB_SECRET_TOKEN }}
              TMDB_API_PUBLIC_KEY: ${{ secrets.TMDB_API_PUBLIC_KEY }}
            ports:
              - 5432:5432
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '25'
                cache: 'maven'

            - name: Maven Wrapper permissions
              run: chmod +x ./mvnw

            - name: Run tests
              env:
                DB_HOST: 127.0.0.1
              run: ./mvnw test

            - name: Build with Maven
              run: ./mvnw clean package -DskipTests

            - name: Login Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: docker build -t pedro084/api-for-evaluating-cinematographic-works:latest .

            - name: Push Docker image
              run: docker push pedro084/api-for-evaluating-cinematographic-works:latest